In [2]:

# !pip install nselib --upgrade

In [3]:
import nselib

In [4]:
# data = nselib.trading_holiday_calendar()
# data

In [5]:
# nselib.capital_market.equity_list().to_csv("nse_equity_list.csv", index=False)

In [6]:
from nselib import capital_market 
capital_market.price_volume_data(symbol='MAGOLD', period="1Y")

Empty DataFrame
Columns: [Symbol, Series, Date, PrevClose, OpenPrice, HighPrice, LowPrice, LastPrice, ClosePrice, AveragePrice, TotalTradedQuantity, Turnover₹, No.ofTrades]
Index: []

In [7]:
pelist = capital_market.pe_ratio(trade_date='15-12-2025')
pelist.sort_values(by='SYMBOLP/E', inplace=True)
pelist[pelist['SYMBOL'].isin(['MAGOLD','AARTIIND','ADANIPORTS','BAJFINANCE','HDFCBANK','ICICIBANK','INFY','TCS','WIPRO'])]

         SYMBOL  SYMBOLP/E  ADJUSTEDP/E
364   ICICIBANK      17.31        17.31
145       WIPRO      20.27        20.27
188    HDFCBANK      21.37        21.09
484         TCS      23.53        23.53
24         INFY      24.32        24.32
671  ADANIPORTS      30.21        29.98
295  BAJFINANCE      35.93        35.93
256    AARTIIND      54.52        55.25

In [8]:
# dir(nselib.capital_market  )

##  https://pypi.org/project/nselib/

In [9]:
# capital_market.price_volume_data(symbol='ITC', from_date='06-12-2025', to_date='11-12-2025')
capital_market.pe_ratio('10-12-2025')

          SYMBOL  SYMBOLP/E  ADJUSTEDP/E
0        THERMAX      50.49        50.49
1         WHEELS      17.74        17.74
2           RIIL     123.75       123.75
3     PREMIERPOL      17.10        17.10
4        RAYMOND      14.25        14.25
...          ...        ...          ...
2070   ITCHOTELS     108.23       108.23
2071     SUPREME     118.17       118.17
2072     PROTEAN      70.87        70.87
2073     MOSCHIP     128.45       128.45
2074   ONESOURCE        NaN       183.80

[2075 rows x 3 columns]

In [10]:

capital_market.price_volume_data(symbol='ITC',
                                 period="1W")

,Symbol,Series,Date,PrevClose,OpenPrice,HighPrice,LowPrice,LastPrice,ClosePrice,AveragePrice,TotalTradedQuantity,Turnover₹,No.ofTrades
0,ITC,EQ,09-Dec-2025,402.30,402.00,404.50,400.00,401.25,401.05,402.28,"94,26,717","3,79,21,90,139.05","1,19,643"
1,ITC,EQ,10-Dec-2025,401.05,401.10,404.40,401.00,403.05,403.15,403.31,"69,69,146","2,81,07,30,997.45","1,06,280"
2,ITC,EQ,11-Dec-2025,403.15,403.15,404.00,401.10,403.00,402.90,402.40,"69,80,147","2,80,88,21,372.05","99,653"
3,ITC,EQ,12-Dec-2025,402.90,402.90,404.00,399.85,400.70,400.10,400.55,"1,24,07,516","4,96,97,85,471.85","1,15,410"
4,ITC,EQ,15-Dec-2025,400.10,400.10,403.35,399.50,402.00,402.30,401.80,"77,56,564","3,11,65,64,595.55","96,420"
5,ITC,EQ,16-Dec-2025,402.30,401.40,405.75,401.05,402.00,401.70,403.11,"1,23,47,384","4,97,73,88,189.80","1,20,140"

In [28]:
capital_market.week_52_high_low_report(trade_date='20-06-2025')
# capital_market.financial_results_for_equity(period="1Y") ## not working

,SYMBOL,SERIES,Adjusted52_Week_High,52_Week_High_Date,Adjusted52_Week_Low,52_Week_Low_DT
0,20MICRONS,EQ,348.00,22-AUG-2024,158.20,12-FEB-2025
1,21STCENMGM,EQ,141.40,11-SEP-2024,57.99,19-JUN-2024
2,360ONE,EQ,1318.00,06-JAN-2025,790.50,07-APR-2025
3,3IINFOLTD,EQ,42.59,08-JUL-2024,20.22,07-APR-2025
4,3MINDIA,EQ,40856.50,02-JUL-2024,25718.15,03-MAR-2025
...,...,...,...,...,...,...
2497,ZOTA,EQ,1078.00,07-FEB-2025,535.00,19-NOV-2024
2498,ZUARI,EQ,268.00,03-DEC-2024,169.20,04-MAR-2025
2499,ZUARIIND,EQ,423.40,08-JUL-2024,229.99,07-APR-2025
2500,ZYDUSLIFE,EQ,1324.30,09-AUG-2024,795.00,07-APR-2025
2501,ZYDUSWELL,EQ,2484.00,30-JUL-2024,1493.20,04-MAR-2025

In [34]:
capital_market.block_deals_data(from_date='15-12-2025', to_date='16-12-2025')

,Date,Symbol,SecurityName,ClientName,Buy/Sell,QuantityTraded,TradePrice/Wght.Avg.Price,Remarks
0,16-DEC-2025,GALLANTT,Gallantt Ispat Limited,GALLANTT INDUSTRY PRIVATE LIMITED,BUY,"12,07,000",590.00,NaN
1,16-DEC-2025,GALLANTT,Gallantt Ispat Limited,KRONE FINSTOCK PRIVATE LIMITED,SELL,"12,07,000",590.00,NaN
2,16-DEC-2025,SBFC,SBFC Finance Limited,238 PLAN ASSOCIATES LLC,SELL,"3,41,770",105.14,NaN
3,16-DEC-2025,SBFC,SBFC Finance Limited,ARANDA INVESTMENTS PTE. LTD.,BUY,"71,33,297",105.14,NaN
4,16-DEC-2025,SBFC,SBFC Finance Limited,MASSACHUSETTS INSTITUTE OF TECHNOLOGY - FDI,SELL,"1,36,36,363",105.14,NaN
5,16-DEC-2025,SBFC,SBFC Finance Limited,MASSACHUSETTS INSTITUTE OF TECHNOLOGY BASIC RE...,SELL,"13,86,387",105.14,NaN
6,16-DEC-2025,SBFC,SBFC Finance Limited,TATA AIA LIFE INSURANCE COMPANY LIMITED,BUY,"82,31,223",105.14,NaN

In [42]:
! pip install nselib --upgrade

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nselib in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (1.9)
Collecting nselib
  Using cached nselib-2.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: requests in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from nselib) (2.32.4)
Requirement already satisfied: pandas in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from nselib) (2.3.2)
Requirement already satisfied: scipy in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from nselib) (1.16.2)
Requirement already satisfied: pandas-market-calendars in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from nselib) (5.1.3)
INFO: pip is looking at multiple versions of nselib to determine which version is compatible with other requirements. This could take a while.
  Using cached nselib-2.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached nselib-2.1-py3-none-any.whl.metadata (5.4 kB)
  Using cached nselib-2.0-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from pandas->nselib) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from pandas->nselib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from pandas->nselib) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from pandas->nselib) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas->nselib) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from requests->nselib) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from requests->nselib) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from requests->nselib) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\perianayagamthirumal\appdata\roaming\python\python313\site-packages (from requests->nselib) (2025.8.3)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
! pip uninstall nselib

^C

In [41]:
from nselib import indices

indices.constituent_stock_list(index_category='BroadMarketIndices', index_name='Nifty 50')

ImportError: cannot import name 'indices' from 'nselib' (C:\Users\PerianayagamThirumal\AppData\Roaming\Python\Python313\site-packages\nselib\__init__.py)