In [1]:
## Use stk.ipynp to compute XIRR

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
file_path = Path('C:\\Users\\111075866\\Downloads\\mf-13.csv')
mf = pd.read_csv(file_path)
mf.describe(include='all')
# mf.head()
#[['Scheme','Inv.Amt','Overall Gain','Inv.Date']]

,Scheme,Latest NAV,Change,Prev NAV,Quantity,Inv. Price,Inv. Date,Inv. Amt,52 Wk High/Low,Todays Gain,Todays Gain%,Overall Gain,Overall Gain%,Realised Gains,Latest Value,Broker,Notes
count,285,286.000000,286.000000,286.000000,286.000000,286.000000,286,2.860000e+02,286,286.000000,286.000000,2.860000e+02,286.000000,0.0,2.860000e+02,286,286
unique,36,NaN,NaN,NaN,NaN,NaN,217,NaN,37,NaN,NaN,NaN,NaN,NaN,NaN,2,3
top,ICICI Pru Multi-Asset Fund - D(G),NaN,NaN,NaN,NaN,NaN,19-04-2022,NaN,762.60 / 577.47,NaN,NaN,NaN,NaN,NaN,NaN,-,-
freq,34,NaN,NaN,NaN,NaN,NaN,6,NaN,34,NaN,NaN,NaN,NaN,NaN,NaN,284,284
mean,NaN,179.667625,1.798177,177.869448,595.557420,110.082543,NaN,2.324896e+04,NaN,558.741259,1.122413,2.087269e+04,60.499371,NaN,4.412165e+04,NaN,NaN
std,NaN,272.043007,2.847585,269.632605,1106.726437,177.693574,NaN,7.971957e+04,NaN,3053.996533,0.892522,1.074294e+05,64.110104,NaN,1.857108e+05,NaN,NaN
min,NaN,14.048700,-0.086700,13.733200,0.000000,0.000000,NaN,0.000000e+00,NaN,-189.000000,-0.170000,-3.610000e+02,-7.220000,NaN,0.000000e+00,NaN,NaN
25%,NaN,27.243000,-0.009000,26.820000,78.825500,16.147250,NaN,5.000010e+03,NaN,-7.000000,-0.030000,1.714250e+03,24.847500,NaN,7.869250e+03,NaN,NaN
50%,NaN,32.694100,0.423000,32.099400,418.460500,22.248150,NaN,9.999996e+03,NaN,159.000000,1.580000,3.869500e+03,45.485000,NaN,1.385500e+04,NaN,NaN
75%,NaN,224.930000,4.727400,219.850000,537.660500,84.571100,NaN,1.000001e+04,NaN,292.000000,1.707500,7.812750e+03,74.462500,NaN,1.784975e+04,NaN,NaN
max,NaN,1235.169000,20.698000,1214.471000,8324.176000,752.845400,NaN,1.236178e+06,NaN,49789.000000,2.350000,1.735041e+06,370.170000,NaN,2.971219e+06,NaN,NaN

In [4]:
# mf.pivot_table(index='', )

In [5]:
mf = pd.DataFrame(mf, columns=['Scheme','Inv.Amt','Overall Gain','Inv.Date'])
mf.groupby(['Scheme']).sum()

                                          Inv.Amt  Overall Gain  Inv.Date
Scheme
ABSL Frontline Eqty-Direct (G)                0.0        400138       0.0
ABSL Liquid Fund - D (G)                      0.0          1880       0.0
BNP Enhanced Equity Hybrid - D (G)            0.0         56425       0.0
Bandhan Government Securities Fund-IP -D      0.0        176232       0.0
CR Bluechip Equity Fund - D (G)               0.0        213997       0.0
DSP Equity Opportunities - Direct (G)         0.0         41448       0.0
Franklin (I) Bluechip - Direct (G)            0.0        288719       0.0
HDFC Balanced Advantage Fund-DP-(G)           0.0        203046       0.0
HDFC Dividend Yield Fund - DP - (D)           0.0         23744       0.0
HDFC Dividend Yield Fund - DP - (G)           0.0        343578       0.0
HDFC MidCap Opport.- Direct (G)               0.0        268623       0.0
HDFC Top 100 Fund - D (G)                     0.0       1735041       0.0
ICICI Pru All Seasons Bond - D (G)            0.0         34140       0.0
ICICI Pru Banking & Finserv - D (G)           0.0         60688       0.0
ICICI Pru Multi-Asset Fund - D(G)             0.0        277591       0.0
ICICI Pru Technology Fund - D (G)             0.0         38294       0.0
ICICI Prudential Equity & Debt - D (G)        0.0         68222       0.0
ICICI Prudential Nifty IT Index Fund-DP-      0.0         14954       0.0
ICICI Prudential Nifty Pharma Index Fund      0.0         20012       0.0
Kotak Gold Fund - Direct (G)                  0.0         74561       0.0
Kotak Nifty Next 50 Index Fund - DP - (G      0.0        162442       0.0
Kotak Small Cap Fund - D (G)                  0.0         72061       0.0
Motilal Oswal Nifty Smallcap 250 Index F      0.0         76133       0.0
Navi Nifty 50 Index Fund - DP - (G)           0.0         17495       0.0
Nippon Gold Savings - Direct (G)              0.0         94262       0.0
PGIM India Flexi Cap Fund - DP (G)            0.0         41446       0.0
PPFAS FCF -DP - (G)                           0.0         62597       0.0
Quant Absolute Fund - Direct (G)              0.0        135650       0.0
Quant Multi Asset Fund - DP (G)               0.0         93547       0.0
Quant Small Cap Fund - DP - (G)               0.0         35004       0.0
SBI - ETF Gold                                0.0          9976       0.0
SBI Contra Fund - Direct (G)                  0.0        139928       0.0
Tata India Pharma & HealthCare -Dir (G)       0.0        122490       0.0
UTI Dividend Yield Fund -Direct (D)           0.0        200857       0.0
UTI Large & Mid Cap Fund - D(G)               0.0         86854       0.0
UTI Mid Cap (G)                               0.0        208939       0.0

In [6]:
mf.

SyntaxError: invalid syntax (3974361729.py, line 1)